### ISSUE TITLE
coffeelint rake task exits early as of 1.10.0

### ISSUE THREAD

**Issue by jonseaberg** [zmbush/coffeelint-ruby#37]
https://github.com/zmbush/coffeelint-ruby/blob/master/lib/tasks/coffeelint.rake#L3
The rake task calls `Coffeelint.run_test_suite` on app and spec.
`success = Coffeelint.run_test_suite('app') and Coffeelint.run_test_suite('spec')`

The new implementation of `Coffeelint.run_test_suite` exits with the number of failures.  This causes the rake task to exit after running `Coffeelint.run_test_suite('app')`.  Is there a reason to exit in run_test_suite?  I can make the changes.  Just wondering how you would like to structure the code.  Another method to run the test suite that can be used by run_test_suite and the rake task, or to remove the exit from run_test_suite, or another option?

**Comment by bolandrm** [comment]
Just ran into the same issue.  The rake task is unusable in 1.10.0.

**Comment by mleone** [comment]
+1

**Comment by zmbush** [comment]
`run_test_suite` should probably return the number of errors rather than exit. Feel free to open a PR.

**Comment by jonseaberg** [comment]
Will do!  Thanks!

**Comment by afestein** [comment]
#38

**Comment by zmbush** [comment]
Apologies for the delay guys. I have just released a version with this fix to rubygems. https://rubygems.org/gems/coffeelint/versions/1.10.0.pre.patch.1

**Comment by afestein** [comment]
Thanks for the prompt response.

**Comment by afestein** [comment]
I just installed the rubygems.org patched version above and this is not resolved for me. 

Although I can see the changes here on Github, when I do a `gem open coffeelint` I can see that the version.rb is reporting "1.10.0" instead of "1.10.0-patch.1", so either I am doing something wrong or there's an issue with the patch? 

Sorry if there is something obvious I am missing.

**Comment by zmbush** [comment]
Did you instal it with `--pre`? It's considered a prerelease gem by rubygems.

**Comment by zmbush** [comment]
`gem install coffeelint --pre -v 1.10.0.pre.patch.1`

**Comment by zmbush** [comment]
As luck would have it, mainline coffeelint just released v1.11.0 I have pushed a new gem for that version (this is no longer a prerelease gem)

**Comment by afestein** [comment]
Thanks so much, working great now.
